---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 7Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: synapse
  labels:
    app: synapse
spec:
  initContainers:
    - name: volume-mount-hack
      image: busybox
      command: ["sh", "-c", "chown -R 991:991 /data"]
      volumeMounts:
        - name: data-volume
          mountPath: /data
  containers:
    - name: synapse
      image: matrixdotorg/synapse
      env:
        - name: SYNAPSE_CONFIG_PATH
          value: "/config/homeserver.yaml"
        - name: SYNAPSE_CONFIG_DIR
          value: "/config"
        - name: TZ
          value: "GMT"
        - name: UID
          value: "991"
        - name: GID
          value: "991"
      volumeMounts:
        - name: config-volume
          mountPath: /config
        - name: data-volume
          mountPath: /data
      ports:
        - containerPort: 8008
    - name: sh
      image: busybox
      command:
        - "/bin/sh"
        - "-c"
        - "--"
      args:
        - "while true; do sleep 30; done;"
      volumeMounts:
        - name: config-volume
          mountPath: /config
        - name: data-volume
          mountPath: /data
  volumes:
    - name: config-volume
      configMap:
        name: homeserverconf
    - name: data-volume
      persistentVolumeClaim:
        claimName: data-pv-claim
  restartPolicy: Always

