apiVersion: miniocontroller.min.io/v1beta1
kind: MinIOInstance
metadata:
  name: synapse-minio
  labels:
    app: trinity
spec:
  credsSecret:
    name: synapse-minio
#  image: minio/minio:RELEASE.2019-09-11T19-53-16Z
  image: minio/minio
  mountPath: /export
  podManagementPolicy: Parallel
  replicas: 1
  liveness:
    httpGet:
      path: /minio/health/live
      port: 9000
    initialDelaySeconds: 120
    periodSeconds: 30
  volumeClaimTemplate:
    metadata:
      name: synapse-minio
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi

