apiVersion: v1
kind: Secret
metadata:
  name: synapse-minio
  labels:
    app: trinity
type: Opaque
data:
  # echo -n "accesskey" | base64
  accesskey: YWNjZXNza2V5
  # echo -n "secretkey" | base64
  secretkey: c2VjcmV0a2V5
